baseURL = "http://iammil.es"
relativeURLs = true
languageCode = "en-us"
title = "https://iammil.es"
theme = "researcher"

[params]
  author = "Miles McDaniel"
  description = "Personal blog for Miles McDaniel"
  favicon = "favicon.ico"  # path to a .ico to use as favicon

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[deployment]

[[deployment.targets]]
name = "iammil.es"
URL = "s3://iammil.es?region=us-west-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID =	"[CLOUDFRONT_DIST_ID]"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
